### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by shontzu** [yuuchin/yuuchin#1]
**B L U E S**
![Blue Mice (Custom)](https://user-images.githubusercontent.com/77496433/135817952-50d27ba1-182b-4ee1-a0c0-95a744410d27.png)
![Curious Mice (Custom)](https://user-images.githubusercontent.com/77496433/135817957-f641d6e7-842a-4fe1-9cec-15ab9b41e0c9.png)
![Heart (Custom)](https://user-images.githubusercontent.com/77496433/135817960-f2938ed5-daf9-46f7-965b-9689961acd67.png)
![Blue Flame (Custom)](https://user-images.githubusercontent.com/77496433/135817963-4de1aeff-6957-427f-92c6-00b02ad6b52b.png)

**P I N K S**
![bullet](https://user-images.githubusercontent.com/77496433/147429169-2b6c6477-1d6c-4bb2-9f3f-f7107e947cd2.png)
![loading](https://user-images.githubusercontent.com/77496433/147426075-c74baebb-ff94-4d57-80a4-4a428c9fd74c.png)
![pinkMunchkin](https://user-images.githubusercontent.com/77496433/147429148-20ac7784-28f0-4666-a478-f896f9febd02.png)

**A D O B E S**
![Ae](https://user-images.githubusercontent.com/77496433/135824829-30f1e558-c108-4ce0-b57c-3f73f00da1d9.png)
![Ai](https://user-images.githubusercontent.com/77496433/135820597-381846aa-f91b-4943-bb51-f003ddaea6bf.png)
![Id](https://user-images.githubusercontent.com/77496433/135820599-ea4acc66-fb72-476d-af73-f33880f2a319.png)
![Pr](https://user-images.githubusercontent.com/77496433/135820600-25bda259-51dc-4a83-840d-f9608f1e7392.png)
![Ps](https://user-images.githubusercontent.com/77496433/135820604-ab3cc803-b72a-45f5-b78e-bc0a8b5fbd9e.png)

**T O O L S**
![Audacity](https://user-images.githubusercontent.com/77496433/135825580-f00e2447-6974-4f09-9861-25ac8cfac5d6.png)
![RD](https://user-images.githubusercontent.com/77496433/135825599-b375f585-d4b9-4e3a-9533-06188e882d26.png)
![SPA ](https://user-images.githubusercontent.com/77496433/135825600-cb1ad671-7a62-4857-afea-763407c51c09.png)
![bootstrap](https://user-images.githubusercontent.com/77496433/135825582-d743f2fd-470b-48b3-8f5e-f45f6fd51894.png)
![BootstrapVue](https://user-images.githubusercontent.com/77496433/148991992-fe4a1a0a-51ca-47fd-9f59-cf24748e2eaf.png)
![VueMaterial](https://user-images.githubusercontent.com/77496433/148991997-743d641e-615e-4aa1-996f-874aa4008750.png)
![Vuesax](https://user-images.githubusercontent.com/77496433/148991999-4d73dc35-603d-4670-b066-9f8ab3c8bdd3.png)
![Vuetify](https://user-images.githubusercontent.com/77496433/148992002-bf2453f7-9fa1-427b-bfe5-eb448e859fcd.png)
![React](https://user-images.githubusercontent.com/77496433/158333806-c8a8f3a2-ffd3-4385-a74b-c802169c8dc3.png)
![Dart](https://user-images.githubusercontent.com/77496433/158334823-388e2e0e-30ea-407f-bbb4-13814b315704.png)
![Flutter](https://user-images.githubusercontent.com/77496433/185775547-3da9804d-687e-4b28-ae3a-dbe17dee7d9c.png)
![download](https://user-images.githubusercontent.com/77496433/135825585-3a849d24-77ee-4110-85cf-9f4e505d0e84.png)
![Mongo](https://user-images.githubusercontent.com/77496433/135825588-7b7463eb-a27e-46f5-925e-70e3b6580a5c.png)
![MySQL](https://user-images.githubusercontent.com/77496433/135825591-f5d821f8-3c50-4157-8018-fc38b1db40df.png)
![node](https://user-images.githubusercontent.com/77496433/135825593-abf0ae8c-853c-4088-a182-ef60f8cd9b18.png)
![php](https://user-images.githubusercontent.com/77496433/135825595-527978e4-b0f7-465f-b10c-6acdb8a559da.png)
![PWA](https://user-images.githubusercontent.com/77496433/135825597-9739732d-ccf6-438e-b7ea-438f99d5c3ce.png)
![vue](https://user-images.githubusercontent.com/77496433/135825573-3922b402-86f5-4ae7-87d0-102b6d1b3bcd.png)
![vim](https://user-images.githubusercontent.com/77496433/135827058-1a910063-37c7-435a-b8bd-d1e4d24c6785.png)
![construct2](https://user-images.githubusercontent.com/77496433/135827059-5894625d-bb6c-4682-8f68-e47e26357671.png)
![git](https://user-images.githubusercontent.com/77496433/135827060-5e2cfe46-ebc4-4311-bedb-b23b45102792.png)
![tmux](https://user-images.githubusercontent.com/77496433/191877390-f0c94aaf-fe36-4e6f-b5ff-fb31a821029e.png)
![unix](https://user-images.githubusercontent.com/77496433/135827052-68eb9dc2-4190-46d2-9674-fe85083cb805.png)
![tailwind](https://user-images.githubusercontent.com/77496433/138993480-2ef3fc45-0993-4e1e-bff9-1dd80d09fe72.png)
![firebase](https://user-images.githubusercontent.com/77496433/139852014-5df685e7-b87e-4477-b6d5-c690077ce9be.png)
![icon-netlify](https://user-images.githubusercontent.com/77496433/147379499-0b044c18-c44f-4aea-957d-d9631543e6e2.png)
![goDaddy](https://user-images.githubusercontent.com/77496433/147379852-8bac895e-94e4-4099-98cc-822e8a66be8a.png)
![Firestore](https://user-images.githubusercontent.com/77496433/148990746-9427251a-8813-4c78-a187-4abc7f7056f5.png)
![Strapi](https://user-images.githubusercontent.com/77496433/149232656-7bbbbf9d-69d6-42f5-a084-82d7970170f3.png)
![Shopify](https://user-images.githubusercontent.com/77496433/149232658-6357debd-0755-467a-8e58-310d000c9149.png)
![PowerBI](https://user-images.githubusercontent.com/77496433/153322505-9d395a56-d743-46bc-bad6-1e43debfb7f4.png)
![SEO](https://user-images.githubusercontent.com/77496433/153441580-879efa75-2384-4f41-8fbe-22bc793c984f.png)
![vercel](https://user-images.githubusercontent.com/77496433/180223310-3ddd910b-ede5-443b-bf97-de48e2cb9a41.jpeg)

**Comment by yuuchin** [comment]
![Blue Flame](https://user-images.githubusercontent.com/77496433/135817501-02af6be8-a15f-4456-bd70-580955ea9223.png)
![Blue Mice](https://user-images.githubusercontent.com/77496433/135817507-0ea9a52c-bfc0-4cfd-a2dc-2adedd4dc9e4.png)
![Curious Mice](https://user-images.githubusercontent.com/77496433/135817508-0f29e882-fa5d-4c0a-8107-498dff4339cf.png)
![Heart](https://user-images.githubusercontent.com/77496433/135817511-d14610ef-14fb-4e2e-b2ed-0cb4a010062c.png)
